hub:
  image: selenium/hub
  ports:
    - "4444:4444"
  extra_hosts:
    &extra-dns-records
    staging.mydomain.com: 127.0.0.1
    test.foo.com: 127.0.0.1
    
firefox:
  image: selenium/node-firefox
  links:
    - hub
  extra_hosts: *extra-dns-records

chrome:
  image: selenium/node-chrome
  links:
    - hub
  extra_hosts: *extra-dns-records
